---
- id: ossindex:pypi:urllib3:8402343062
  title: "[CVE-2016-9015] Versions 1.17 and 1.18 of the Python urllib3 library suffer
    from a vulnerability..."
  description: Versions 1.17 and 1.18 of the Python urllib3 library suffer from a
    vulnerability that can cause them, in certain configurations, to not correctly
    validate TLS certificates. This places users of the library with those configurations
    at risk of man-in-the-middle and information leakage attacks. This vulnerability
    affects users using versions 1.17 and 1.18 of the urllib3 library, who are using
    the optional PyOpenSSL support for TLS instead of the regular standard library
    TLS backend, and who are using OpenSSL 1.1.0 via PyOpenSSL. This is an extremely
    uncommon configuration, so the security impact of this vulnerability is low.
  affected_package: urllib3
  vulnerable_versions:
  - '1.17'
  - '1.18'
  package_manager: pypi
  cve:
  - CVE-2016-9015
  disclosed_date: 2017-01-11
  created_date: 2017-01-11
  last_modified_date: 2017-01-13
  credit:
  - OSSIndex
  references:
  - http://www.openwall.com/lists/oss-security/2016/10/27/6
  - http://www.securityfocus.com/bid/93941
  source_url: https://ossindex.net/resource/package/8401376142/vulnerabilities
- id: snykio:pypi:urllib3:174323
  title: CRLF injection
  description: |
    [urllib3][1] is an HTTP library with thread-safe connection pooling,
    file post, and more.

    Affected versions of this package are vulnerable to CRLF injection.
    Attacker who has the control of the requesting address parameter, could
    manipulate an HTTP header and attack an internal service.



    [1]: https://pypi.org/project/urllib3/
  affected_package: urllib3
  vulnerable_versions:
  - "< 1.24.3"
  severity: high
  package_manager: pypi
  cve:
  - CVE-2019-11236
  cwe:
  - CWE-93
  disclosed_date: 2019-04-15
  created_date: 2019-04-18
  last_modified_date: 2019-04-18
  credit:
  - ragdoll
  references:
  - https://bugs.python.org/issue36276
  - https://github.com/urllib3/urllib3/commit/5d523706c7b03f947dc50a7e783758a2bfff0532
  - https://github.com/urllib3/urllib3/issues/1553
  - https://github.com/urllib3/urllib3/pull/1487
  - https://github.com/urllib3/urllib3/pull/1531
  source_url: https://snyk.io/vuln/SNYK-PYTHON-URLLIB3-174323
- id: snykio:pypi:urllib3:174464
  title: Improper Certificate Validation
  description: |
    [urllib3][1] is an HTTP library with thread-safe connection pooling,
    file post, and more.

    Affected versions of this package are vulnerable to Improper Certificate
    Validation. It mishandles certain cases where the desired set of CA
    certificates is different from the OS store of CA certificates. This can
    result in SSL connections succeeding in situations where it should have
    failed.



    [1]: https://pypi.org/project/urllib3/
  affected_package: urllib3
  vulnerable_versions:
  - "< 1.24.2"
  severity: high
  package_manager: pypi
  cve:
  - CVE-2019-11324
  cwe:
  - CWE-295
  disclosed_date: 2019-04-18
  created_date: 2019-04-18
  last_modified_date: 2019-04-18
  credit:
  - Unknown
  references:
  - https://github.com/urllib3/urllib3/compare/a6ec68a...1efadf4
  source_url: https://snyk.io/vuln/SNYK-PYTHON-URLLIB3-174464
- id: snykio:pypi:urllib3:40441
  title: Improper Certificate Validation
  description: |
    [`urllib3`][1] is a HTTP library with thread-safe connection pooling,
    file post, and more.

    Affected versions of this package fail to validate TSL certificates in
    certain configurations. This places users of the library with those
    configurations at risk of man-in-the-middle and information leakage
    attacks. This vulnerability affects users using versions 1.17 and 1.18
    of the urllib3 library, who are using the optional PyOpenSSL support for
    TLS instead of the regular standard library TLS backend, and who are
    using OpenSSL 1.1.0 via PyOpenSSL. This is an extremely uncommon
    configuration, so the security impact of this vulnerability is low.



    [1]: https://pypi.python.org/pypi/urllib3
  affected_package: urllib3
  vulnerable_versions:
  - ">= 1.17 < 1.18.1"
  severity: low
  package_manager: pypi
  cve:
  - CVE-2016-9015
  cwe:
  - CWE-295
  disclosed_date: 2016-10-27
  created_date: 2016-10-27
  last_modified_date: 2016-10-27
  credit:
  - Cory Benfield
  references:
  - https://github.com/shazow/urllib3/commit/5e36a7096455ea94fb28b623d64e1f1bad97f822
  - https://github.com/shazow/urllib3/pull/1010
  - https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2016-9015
  source_url: https://snyk.io/vuln/SNYK-PYTHON-URLLIB3-40441
- id: snykio:pypi:urllib3:559452
  title: Denial of Service (DoS)
  description: |+
    [urllib3][1] is a HTTP library with thread-safe connection pooling, file
    post, and more.

    Affected versions of this package are vulnerable to Denial of Service
    (DoS). The `_encode_invalid_chars` function in `util/url.py` in the
    urllib3 allows a denial of service (CPU consumption) because of an
    inefficient algorithm. The percent\_encodings array contains all matches
    of percent encodings. It is not deduplicated. For a URL of length N, the
    size of percent\_encodings may be up to O(N). The next step (normalize
    existing percent-encoded bytes) also takes up to O(N) for each step, so
    the total time is O(N^2). If percent\_encodings were deduplicated, the
    time to compute \_encode\_invalid\_chars would be O(kN), where k is at
    most 484 ((10+6\*2)^2).



    [1]: https://pypi.org/project/urllib3/
    \nDenial of Service (DoS) describes a family of attacks, all aimed at
    making a system inaccessible to its intended and legitimate users.

    Unlike other vulnerabilities, DoS attacks usually do not aim at
    breaching security. Rather, they are focused on making websites and
    services unavailable to genuine users resulting in downtime.

    One popular Denial of Service vulnerability is DDoS (a Distributed
    Denial of Service), an attack that attempts to clog network pipes to the
    system by generating a large volume of traffic from many machines.

    When it comes to open source libraries, DoS vulnerabilities allow
    attackers to trigger such a crash or crippling of the service by using a
    flaw either in the application code or from the use of open source
    libraries.

    Two common types of DoS vulnerabilities:

    * High CPU/Memory Consumption- An attacker sending crafted requests that
      could cause the system to take a disproportionate amount of time to
      process. For example,
      [commons-fileupload:commons-fileupload](SNYK-JAVA-COMMONSFILEUPLOAD-30082).

    * Crash - An attacker sending crafted requests that could cause the
      system to crash. For Example, [npm `ws` package](npm:ws:20171108)

  affected_package: urllib3
  vulnerable_versions:
  - ">= 1.25.2 < 1.25.8"
  severity: medium
  package_manager: pypi
  cve:
  - CVE-2020-7212
  cwe:
  - CWE-400
  disclosed_date: 2020-03-06
  created_date: 2020-03-06
  last_modified_date: 2020-03-06
  credit:
  - Unknown
  references:
  - https://github.com/urllib3/urllib3/commit/a2697e7c6b275f05879b60f593c5854a816489f0
  - https://github.com/urllib3/urllib3/commit/a74c9cfbaed9f811e7563cfc3dce894928e0221a
  source_url: https://snyk.io/vuln/SNYK-PYTHON-URLLIB3-559452
- id: snykio:pypi:urllib3:72681
  title: Authentication Bypass
  description: |
    [urllib3][1] is a HTTP library with thread-safe connection pooling, file
    post, and more.

    Affected versions of this package are vulnerable to Authentication
    Bypass. It did remove the Authorization HTTP header when following a
    cross-origin redirect. This can allow for credentials in the
    Authorization header to be exposed to unintended hosts or transmitted in
    cleartext.



    [1]: https://pypi.org/project/urllib3/
  affected_package: urllib3
  vulnerable_versions:
  - "< 1.23"
  severity: medium
  package_manager: pypi
  cve:
  - CVE-2018-20060
  cwe:
  - CWE-288
  disclosed_date: 2018-12-11
  created_date: 2018-12-12
  last_modified_date: 2018-12-12
  credit:
  - Unknown
  references:
  - https://bugzilla.redhat.com/show_bug.cgi?id=1649153
  - https://github.com/urllib3/urllib3/issues/1316
  - https://github.com/urllib3/urllib3/pull/1346
  source_url: https://snyk.io/vuln/SNYK-PYTHON-URLLIB3-72681
